[package]
name = "pic-pca"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "pic_pca"

[dependencies]
serde.workspace = true
serde_json.workspace = true
serde_bytes.workspace = true
ciborium.workspace = true